force-app/main/default/objects/Report_Section__c/Report_Section__c.object-meta.xml
<CustomObject>
    <label>Report Section</label>
    <nameField>
        <label>Report Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Section__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>disco__Form__c</referenceTo>
    <relationshipLabel>Report Sections</relationshipLabel>
    <relationshipName>Report_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Section__c/fields/Section_content__c.field-meta.xml
<CustomField>
    <fullName>Section_Content__c</fullName>
    <label>Section Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Report_Section__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Report Sections</relationshipLabel>
    <relationshipName>Report_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Section_List__c/Report_Section_List__c.object-meta.xml
<CustomObject>
    <label>Report Section List</label>
    <nameField>
        <label>Report Section List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Section Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Section_List__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>ddm__dmsfc_Form__c</referenceTo>
    <relationshipLabel>Report Section Lists</relationshipLabel>
    <relationshipName>Report_Section_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Section_List__c/fields/Report_Section__c.field-meta.xml
<CustomField>
    <fullName>Report_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Report Section</label>
    <referenceTo>Report_Section__c</referenceTo>
    <relationshipLabel>Report Section Lists</relationshipLabel>
    <relationshipName>Report_Section_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Section_List__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Report Section Lists</relationshipLabel>
    <relationshipName>Report_Section_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReportSectionPicker.cls
public without sharing class ReportSectionPicker
{
    @AuraEnabled(cacheable=true)
    public static List<Report_Section__c> getReportSections(Id workOrderId, Id formId)
    {
        System.debug('workOrderID = ' + workOrderId);
        List<Report_Section__c> results = [SELECT Id, Name, Section_Content__c FROM Report_Section__c WHERE Work_Order__c = :workOrderId AND Form__c = :formId ORDER BY CreatedDate];
        
        System.debug('Results: ' + results);
        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<Report_Section_List__c> getSelectedSections(Id workOrderId, Id formId)
    {
        System.debug('workOrderID = ' + workOrderId);
        List<Report_Section_List__c> results = [SELECT Id, Name, Form__c, Work_Order__c, Report_Section__c, Sequence__c, Section_Content__c FROM Report_Section_List__c WHERE Work_Order__c = :workOrderId AND Form__c = :formId ORDER BY Sequence__c];
        System.debug('Results: ' + results);
        return results;
    }
}